services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: oragon-rabbitmq-demos
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
